apiVersion: v1
kind: Secret
metadata:
  annotations:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "nginx.fullname" . }}
type: Opaque
data:
  password: {{ .Values.mysecret.password | b64enc | quote }}
