name: Docker Image CI
on:
  push:
    branches: [ github-ci ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2 # may be actions/checkout@v2 now
        - name: Login to DockerHub Registry
          run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }} ${{ secrets.DOCKERHUB_REG }}
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the tagged Docker image
          run: docker build . --file /docker/python/Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/omega:${{steps.vars.outputs.tag}}
        - name: Push the tagged Docker image
          run: docker push ${{ secrets.DOCKERHUB_USER }}/omega:${{steps.vars.outputs.tag}}
